### PR TITLE
Allow Symfony 3

### PR DESCRIPTION
**Pull request by barryvdh**

### CODE REVIEW

**Comment by asm89** [comment]
Thank you @barryvdh

**Comment by barryvdh** [comment]
Thanks, should this be a new tag?
(Note: I haven't tested this yet fully, but 3.x should be compatible with 2.8)

**Comment by asm89** [comment]
@barryvdh I'll tag when one of us finds time to actually test it. Until that time I hope that folks are at least unblocked on installing it. :)

**Comment by moshie** [comment]
:+1: Thanks guys for sorting this!

**Comment by barryvdh** [comment]
@moshie Did you test this correctly on Laravel 5.2 or Symfony 3?

**Comment by moshie** [comment]
@barryvdh Laravel 5.2 Unfortunately still getting the same messages.. 

```
  Problem 1
    - Conclusion: don't install barryvdh/laravel-cors v0.7.3
    - Installation request for symfony/http-foundation == 3.0.0.0 -> satisfiable by symfony/http-foundation[v3.0.0].
    - Conclusion: remove laravel/framework v5.2.5
    - Conclusion: don't install laravel/framework v5.2.5
    - barryvdh/laravel-cors v0.7.0 requires illuminate/support ~5.0.14|5.1.x -> satisfiable by illuminate/support[v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.6, v5.1.8
].
    - barryvdh/laravel-cors v0.7.1 requires illuminate/support ~5.0.14|5.1.x -> satisfiable by illuminate/support[v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.6, v5.1.8
].
    - barryvdh/laravel-cors v0.7.2 requires illuminate/support ~5.0.14|5.1.x -> satisfiable by illuminate/support[v5.0.22, v5.0.25, v5.0.26, v5.0.28, v5.0.33, v5.1.1, v5.1.13, v5.1.16, v5.1.2, v5.1.20, v5.1.22, v5.1.25, v5.1.6, v5.1.8
].
    - don't install illuminate/support v5.1.8|don't install laravel/framework v5.2.5
    - Installation request for laravel/framework == 5.2.5.0 -> satisfiable by laravel/framework[v5.2.5].
    - Installation request for barryvdh/laravel-cors 0.7.x -> satisfiable by barryvdh/laravel-cors[v0.7.0, v0.7.1, v0.7.2, v0.7.3].
```

Merry Christmas btw :)

**Comment by GrahamCampbell** [comment]
Not a bug actually.

**Comment by GrahamCampbell** [comment]
It's because a release has not been tagged yet. Simple add do this for now: https://github.com/cachethq/Cachet/blob/master/composer.json#L27-L28

**Comment by barryvdh** [comment]
Zo Graham, this is all good now? Then this can be tagged, and perhaps a branch alias should be added to the composer file.

**Comment by GrahamCampbell** [comment]
I agree that would be a good idea to have.

**Comment by GrahamCampbell** [comment]
If we had a branch alias I could have just written `~0.2.2`.

**Comment by barryvdh** [comment]
@asm89 can you tag this?

**Pull request merged**
