### PR TITLE
Use a non-deprecated autoloading standard

### PR DESCRIPTION
**Pull request by GrahamCampbell**

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Ping @asm89.

**Comment by GrahamCampbell** [comment]
Ping @asm89.

**Comment by GrahamCampbell** [comment]
Ping @asm89.

**Comment by GrahamCampbell** [comment]
Ping @asm89.

**Comment by GrahamCampbell** [comment]
Ping @asm89.

**Comment by asm89** [comment]
Got a reference that PSR-0 is deprecated? I haven't been active anymore in the PHP community for a while, but I cannot find the answer on getcomposer.org.

**Comment by GrahamCampbell** [comment]
> Got a reference that PSR-0 is deprecated? I haven't been active anymore in the PHP community for a while, but I cannot find the answer on getcomposer.org.

Yes. The official standards website. By definition, psr-4 replaces and deprecates psr-0.

**Comment by GrahamCampbell** [comment]
Been deprecated since 2014.

image

http://www.php-fig.org/psr/psr-0/

**Comment by GrahamCampbell** [comment]
New PR at https://github.com/asm89/stack-cors/pull/37.

**Pull request closed without merging**
