### PR TITLE
Bump phpunit and PSR standards

### PR DESCRIPTION
**Pull request by barryvdh**
Bring phpunit up-to-date, fix PSR-4 autoload en move the tests a bit.

### CODE REVIEW

**Comment by barryvdh** [comment]
@davidbarratt PHP 7.0 is okay for Drupal, right? I'd rather bump to 7.1 but I guess this if fine too.

**Comment by davidbarratt** [comment]
> @davidbarratt PHP 7.0 is okay for Drupal, right? I'd rather bump to 7.1 but I guess this if fine too.

Yep. :) https://www.drupal.org/docs/8/system-requirements/php-requirements

**Comment by barryvdh** [comment]
But is v2 required for Drupal 8, or just Drupal 9? Otherwise we can bump to 7.1 and add better typehints.

**Comment by davidbarratt** [comment]
> But is v2 required for Drupal 8, or just Drupal 9? Otherwise we can bump to 7.1 and add better typehints.

I don't even know if v2 will make it into Drupal 9. :/

The minimum required version of PHP for Drupal 8.x is 7.0.8. It looks like Drupal 9 will require at least 7.3.

**Comment by davidbarratt** [comment]
I have conflicting documentation on if upgrading to v2 is a bc-break or not.

On one hand, major upgrades of libraries **is** is a BC break:
https://www.drupal.org/core/d8-allowed-changes#minor

On the other hand, change(s) to an HTTP Header is **not** a BC break:
https://www.drupal.org/core/d8-bc-policy#http

I'll ask on their task, since Drupal 9.0.0 is already in beta2, it's unlikely that it would get into that version. Therefore, if it's accaptable to be added to 9.1.0, it's also accaptable to be added to 8.9.0

**Comment by davidbarratt** [comment]
If it can't be added to Drupal 9.1 (or 9.0 for that matter), I'll open a task here to back-port the functionality to the 1.x branch behind a `bc` flag like `bcCacheVary` which will default to `true` and users can change it to `false` to opt-into the new behavoir.

**Pull request merged**
