### PR TITLE
Allow Symfony 6

### PR DESCRIPTION
**Pull request by barryvdh**

### CODE REVIEW

**Comment by asm89** [comment]
LGTM, but CI didn't actually test with 6.x. I assume the Symfony http-{foundation,kernel} packages to be fine.

**Comment by barryvdh** [comment]
Looks like the signature changed though. So needs some work still

**Comment by barryvdh** [comment]
I've had to change it because the signature changes. Only supports Symfony 6.x now; https://github.com/asm89/stack-cors/commit/8b27af9955b5b587da2eab7f3c0dac3c5352a428
But created a 2.0 branch to support older versions if required.

**Comment by driesvints** [comment]
@barryvdh guess we should update master on laravel/laravel to v2.1.0?

**Comment by barryvdh** [comment]
I don't think that's required. The signature only applies to Cors.php, which we don't use. We use CorsService directly, which doesn't include the handle method. However, both 2.0.x and 2.1.x should work, so Composer will just pick the latest version if possible anyway.

**Pull request merged**
