### PR TITLE
Check for same origin as host

### LINKED ISSUE #10: False positives when detecting CORs Request
A [discussion](https://github.com/barryvdh/laravel-cors/pull/21) with the developers of [laravel-cors](https://github.com/barryvdh/laravel-cors) and [TrustedProxy](https://github.com/fideloper/TrustedProxy) lead me to believe that there are cases when stack-cors is miss identifying a request as CORS request.

In `CorsService::isCorsRequest()` the request is only check for an existing  'Origin' header.

Should this function not all all check if the contents of the 'Origin' match the Scheme and  host of the request as well?

Example:

```
public function isCorsRequest(Request $request)
{
    return $request->headers->has('Origin') &&
           $request->headers->get('Origin') != $request->getSchemeAndHttpHost();
}
```

Right now, @barryvdh does this check when register his ServiceProvider in [laravel-cors](https://github.com/barryvdh/laravel-cors/blob/master/src/CorsServiceProvider.php#L37). This early cross-origin check seems to be incompatible with other ServiceProviders like @fideloper 's [TrustedProxy](https://github.com/fideloper/TrustedProxy). 

Would it make more sense to do the  cross-origin check in your middleware instead? Or is there a case when CORS hander would need to trigger for a request with matching  scheme and host.

### PR DESCRIPTION
**Pull request by barryvdh**
Skip when they are the same. Fixes #10

### CODE REVIEW

**Comment by GromNaN** [comment]
:+1: The current host should not be restricted.

Chrome sends the **Origin** header for non-GET requests, even if not AJAX.
http://stackoverflow.com/questions/22198581/origin-header-is-present-in-non-get-requests-in-chrome-app-even-if-the-server-do

@barryvdh You should squash your commits.

**Comment by wimleers** [comment]
@barryvdh Can you squash your commits? Then let's get this merged ASAP.

This problem has existed for 2.5 years at this point…

**Comment by barryvdh** [comment]
Uhh, I could, but I didn't receive any feedback in those 2.5 years. And the author can just squash + merge with a single button.

**Comment by barryvdh** [comment]
Alrighty, I created a `isSameHost($request)` function to improve readability and squashed/rebased so it's 1 commit. Tests should also be good.

Not sure what the hold up is. I've been using this for 2,5 in https://github.com/barryvdh/laravel-cors so decided to fork this library due to inactivity.

**Comment by navneet0693** [comment]
This seriously needs to get merged ASAP.

**Comment by dawehner** [comment]
<3

**Comment by chris-hamper** [comment]
🎉  @asm89 thanks for getting this merged! Any chance you could tag a new release with the latest fixes included? Once that's done we can pull them into Drupal.

**Comment by barryvdh** [comment]
@chris-hamper It is tagged :) 
https://github.com/asm89/stack-cors/releases/tag/1.1.0

**Pull request merged**
