### PR TITLE
Use modern autoloading standard

### PR DESCRIPTION
**Pull request by GrahamCampbell**
Replaces https://github.com/asm89/stack-cors/pull/20.

### CODE REVIEW

**Comment by barryvdh** [comment]
All in favor for PSR-4, but rather have the files directly in src/tests now.

**Comment by ConnorVG** [comment]
I think it'd make more sense to use:
```json
"psr-4": {
    "Asm89\\Stack\\": "src/"
}
```

Then remove the silly folder structure, making `Asm89\Stack` the first class namespace.

**Comment by barryvdh** [comment]
Yeah that's what I meant :P

**Comment by GrahamCampbell** [comment]
> Yeah that's what I meant :P

Doing that is a breaking change. There's no reason to assume that things are autoloaded or even installed using composer, and even then, people may be making an assumption on where the files are located, such as in a custom laravel optimize file.

**Comment by barryvdh** [comment]
> There's no reason to assume that things are autoloaded or even installed using composer, and even then,
The only suggested installation method is Composer. I don't see why this would be manually loaded. Especially in the contect of Symfony HttpFoundation/stack middlewares.

Imho, file paths are not public api. So as long as the namespace doesn't change I wouldn't consider it a breaking change. Custom laravel optimize files are out of scope imho. This will land in 1.1 so is a minor version bump, and if you do edge things like optimizing on 3rd party code, you should probably be more strict about it.

**Comment by asm89** [comment]
Let's go ahead and switch to PSR-4. I'd like to have the move discussion somewhere else.

**Comment by ConnorVG** [comment]
You may win this battle @GrahamCampbell... I'm not out of poké balls yet 😉

**Pull request merged**
