### PR TITLE
Move to PSR-4 Autoloading

### PR DESCRIPTION
**Pull request by ConnorVG**
Replaces #37

See here: https://github.com/asm89/stack-cors/pull/37#issuecomment-293179127

### CODE REVIEW

**Comment by GrahamCampbell** [comment]
Moving the files is a breaking change.

**Comment by ConnorVG** [comment]
@GrahamCampbell on the off chance that someone tries to directly access the files via the filesystem, sure. This really defeats the point of autoloading, though.

**Comment by GrahamCampbell** [comment]
This will break Laravel 4, due to the compiled file generation.

**Comment by ConnorVG** [comment]
@GrahamCampbell how will it? A composer update will recompile the 'compiled' file in Laravel 4, will it not?

**Comment by GrahamCampbell** [comment]
No. Thefile paths have changed, which is why it is breaking. This is why I did not change them.

**Comment by ConnorVG** [comment]
https://github.com/laravel/laravel/blob/v4.2.11/composer.json#L25-L28

I'm fairly sure they will be fine...

**Comment by GrahamCampbell** [comment]
No.

**Comment by ConnorVG** [comment]
Explain how this is the case. "No" isn't a reasonable response now is it?

**Comment by GrahamCampbell** [comment]
Actually, this looks like another dependency, but my point remains. This IS breaking.

https://github.com/laravel/framework/blob/4.2/src/Illuminate/Foundation/Console/Optimize/config.php#L118

**Comment by ConnorVG** [comment]
Man, that is such a stupid way to utilise vendors. Change of directory structure shouldn't be a BC issue. This should be generated, not static.

My point stands, this doesn't break Laravel 4 and "on the off chance that someone tries to directly access the files via the filesystem, sure. This really defeats the point of autoloading, though."

**Comment by GrahamCampbell** [comment]
There's no reason to assume that this package is even installed by composer, and since it does not provide it's own autoloader, this is a breaking change.

**Comment by ConnorVG** [comment]
If it's not installed via composer that means it would require manually updating (retrieval and extraction) – this means any file structure changes would be caught first-class. That's a non-issue.

**Comment by GrahamCampbell** [comment]
No, that's not true.

**Comment by ConnorVG** [comment]
How is that not true? If there is no provided autoloader and it's not installed via composer that means it needs another retrieval method (which this package doesn't state support for).

If that other retrieval method is manual then this would be caught immediately. If not then this would be caught during initial testing.

**Comment by GrahamCampbell** [comment]
Breaking the code, and then saying, well you should have noticed we broke it, is a poor excuse.

**Comment by ConnorVG** [comment]
Installing by a non-supported method then complaining that the method you used no longer works out-of-the box is a poor complaint.

image

**Comment by GrahamCampbell** [comment]
Just because you installed it using composer, it still does not mean that moving the files is allowed. This breaks one of my laravel applications, and I installed it through composer.

**Comment by ConnorVG** [comment]
Is that because you decided to utilise it in a non-standard way? Say, via ClassPreloader? Seems more like an issue with ClassPreloader than any package it is used on.

**Comment by barryvdh** [comment]
@GrahamCampbell How did it break your app? Because of optimizing those files?

**Comment by ConnorVG** [comment]
Because of a specific use case via an optimising route.

My opinion would be: major version bump (assuming we're utilising semver here).

**Comment by barryvdh** [comment]
(Copying in from https://github.com/asm89/stack-cors/pull/37#issuecomment-293213873)
> There's no reason to assume that things are autoloaded or even installed using composer, and even then,

The only suggested installation method is Composer. I don't see why this would be manually loaded. Especially in the contect of Symfony HttpFoundation/stack middlewares.

Imho, file paths are not public api. So as long as the namespace doesn't change I wouldn't consider it a breaking change. Custom laravel optimize files are out of scope imho. This will land in 1.1 so is a minor version bump, and if you do edge things like optimizing on 3rd party code, you should probably be more strict about it. (Agreeing to https://www.reddit.com/r/PHP/comments/1xs0ok/psr4_and_semver/ here)

**Comment by asm89** [comment]
What's the benefit of the file move? It will also break VCS history, so I'm not a fan unless someone can give a very good reason to do so. :)

**Comment by barryvdh** [comment]
No practical benefit other the purity. But I would close this and use the other one from Graham. 
We can do this for v2.

**Pull request closed without merging**
