### PR TITLE
Support Symfony 7.

### PR DESCRIPTION
**Pull request by longwave**
Symfony has dropped the `MASTER_REQUEST` constant in Symfony 7 so we have to switch to `MAIN_REQUEST` and drop support for older versions of Symfony.

### CODE REVIEW

**Comment by barryvdh** [comment]
It's deprecated since 5.3, so we could still support 5.3 and above right?

**Comment by barryvdh** [comment]
https://github.com/symfony/http-kernel/blob/v5.3.0/HttpKernelInterface.php

**Comment by barryvdh** [comment]
Sorry for the noise, was struggling a bit with the dependencies for the tests. I think this is probably the cleanest. Drop support for PHP < 7.3 and Symfony < 5.3. 
This would allow support for Drupal 9 still, although that seems to be end-of-life.

We could also just skip ahead to PHP8.1 and Symfony 6 though.

**Comment by longwave** [comment]
Thanks for fixing up the test runner config. I forgot that Symfony allowed the deprecation to span two major versions so 5.3 seems fine as a new minimum.

Drupal 9 uses Symfony 4 which is why it is end of life now. Drupal 11 will be using Symfony 7 and we are looking to start work on the development branch of that, which is the reason I opened this PR.

**Comment by longwave** [comment]
Also added argument types to the method, given that they are now on the interface since at least 5.3.

**Comment by barryvdh** [comment]
Drupal 10 is Symfony 6 right? So I guess we could drop some legacy versions.

**Comment by longwave** [comment]
Yes, Drupal 10 uses Symfony 6; we skipped Symfony 5.

**Comment by barryvdh** [comment]
Thanks@

**Comment by barryvdh** [comment]
I've bumped the version alias to 2.2-dev so you can prepare/test with Drupal. I'll tag a new release (2.2.0) after feedback.

**Comment by andypost** [comment]
Thank you, works for me with SF 7.0 RC2

**Comment by barryvdh** [comment]
Tagged https://github.com/asm89/stack-cors/releases/tag/v2.2.0

**Comment by andypost** [comment]
Thank you a lot! Just in time) https://github.com/symfony/symfony/releases/tag/v7.0.0

**Pull request merged**
